@startuml
'https://plantuml.com/ru/class-diagram

enum Symbol {
    X
    O
}

class Cell {
    int Row
    int Column
}

class Move {
    Cell Cell
    Symbol Symbol
}

class Field {
    - Symbol?[] _symbols
    + Apply(move)
    + IEnumerable<Cell> GetEmptyCells()
    + Symbol? GetWinner()
}

interface IPlayer {
    Symbol symbol
    Move(game)
}

class Player {
}

class AIPlayer {
}

' раунд игры, счет?

class Game {
    - Field field
    - IPlayer xPlayer
    - IPlayer oPlayer
    + IPlayer CurrentPlayer
}

Move --> Symbol
Move --> Cell
Field o-- Symbol
Field ..> Move
Player ..|> IPlayer
AIPlayer ..|> IPlayer
IPlayer --> Move
Game ..> Field
Game --> IPlayer

@enduml