@startuml
'https://plantuml.com/ru/sequence-diagram

Player -> Game : NextMove
Game -> Field : ApplyMove
Game -> Field : GetWinner

alt winner exists

    Field --> Game: Winner
    Game --> Player : GameOver

else if no winner
    
    Game -> Field : GetEmptyCells
    alt no empty cells
        Game --> Player : GameOver
    else has empty cells
        Game -> Game : SwitchPlayer
        Player -> Game : NextMove
    end
    
end
 
@enduml