@startuml
'https://plantuml.com/ru/sequence-diagram

Player -> Game : NextMove
Game -> Field : GetWinner

alt winner exists

    Field -> Game: Winner
    Game -> Player : GameOver

else if no winner
    
    Game -> Field : IsDraw
    alt is draw
        Game -> Player : GameOver
    else if no draw
        Game -> Game : SwitchPlayer
        Player -> Game : NextMove
    end
    
end
 
@enduml